import { CatalogRow } from '@/lib/types';

export const sampleCatalog: CatalogRow[] = [
  {
    roasterBeanId: 'rb-001',
    roasterName: 'Captain George',
    city: 'Guiyang',
    beanName: 'Ethiopia Yirgacheffe G1',
    displayName: 'Black Cat Blend - Ethiopia Lot',
    processMethod: 'Washed',
    roastLevel: 'Light',
    priceAmount: 128,
    priceCurrency: 'CNY',
    isInStock: true,
    status: 'ACTIVE',
    salesCount: 100,
  },
  {
    roasterBeanId: 'rb-002',
    roasterName: 'Rightpaw Coffee',
    city: 'Shanghai',
    beanName: 'Colombia Pink Bourbon',
    displayName: 'Pink Bourbon Turbo',
    processMethod: 'Anaerobic',
    roastLevel: 'Light',
    priceAmount: 168,
    priceCurrency: 'CNY',
    isInStock: false,
    status: 'ACTIVE',
    salesCount: 50,
  },
  {
    roasterBeanId: 'rb-003',
    roasterName: 'Terraform',
    city: 'Shanghai',
    beanName: 'Panama Geisha',
    displayName: 'Festival Reserve Geisha',
    processMethod: 'Natural',
    roastLevel: 'Light',
    priceAmount: 260,
    priceCurrency: 'CNY',
    isInStock: true,
    status: 'DRAFT',
    salesCount: 0,
  },
];
